package exception_handling;

 class trycatch {
    public static void main(String args[]) throws ArithmeticException
    {
        //try
        {
            int i=10/0;

            System.out.println("hello");
        }
        /*catch(Exception e)
        {
            System.out.println(e);
        }
        finally
        {

            System.out.println("Finally block is always executed");
        }*/
    }


}
